### ISSUE TITLE
Amazing EFI,about i5 10210U

### ISSUE THREAD

**Issue by Kayro11** [tdsf/T14sGen1_hackintosh#2]
Hello,My T14 gen1 is i5 10210U and the GPU is the same UHD620. Can I use it directly?

**Comment by tdsf** [comment]
Hey there, for the T14 I would recommend other EFI (see my thanking notes, Baio1977 and askwakhid). The USB mapping is different. However it should work.
I have installed mine with this EFI directly in the USB drive.
